modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
issueTrackerURL="http://github.com/itsmeow/BetterTridentReturn/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/bettertridentreturn" #optional
logoFile="bettertridentreturn.png" #optional
credits="its_meow: everything" #optional
authors="its_meow" #optional
license="MIT"
[[mods]] #mandatory
modId="bettertridentreturn" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Trident Return" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Makes the Loyalty enchantment return the trident to the slot it left rather than just the first available slot.'''